var se = {
    Save: "Spara",
    "Save all": "Spara allt",
    Rename: "Döp om",
    Open: "Öppna",
    Edit: "Editera",
    Delete: "Radera",
    Folder: "Mapp",
    "Add New": "Lägg till ny",
    Size: "Storlek",
    Date: "Datum",
    "back to parent folder": "tillbaka till överordnad mapp",
    Download: "Ladda ner",
    Type: "Typ",
    Information: "Information",
    Files: "Filer",
    Table: "Tabell",
    Cards: "Kort",
    Total: "Totalt",
    "Are you sure ?": "Är du säker?",
    Details: "Detaljer",
    "Enter a new name": "Skriv nytt namn",
    Add: "Lägg till",
    "Select something": "Välj någonting",
    "Download file": "Ladda ner fil",
    Preview: "Förhandsgranska",
    Refresh: "Uppdatera",
    "Are you sure you want to exit without saving?": "Är du säker på att du vill avsluta utan att spara?",
    "Save before closing?": "Spara innan du stänger?",
    Copy: "Kopiera",
    Cut: "Klipp ut",
    Paste: "Klistra in",
    "Deleting...": "Raderar...",
    "Copying...": "Kopierar...",
    "Moving...": "Flyttar...",
    Folders: "Mappar",
    "Search results": "Sökresultat",
    "Search results in": "Sökresultat i",
    "Search files and folders": "Sök efter filer och mappar",
    "Add new file": "Lägg till ny fil",
    "Add new folder": "Lägg till ny mapp",
    "Upload file": "Ladda up fil",
    folder: "mapp",
    file: "fil",
    archive: "arkiv",
    audio: "ljud",
    image: "bild",
    video: "video",
    code: "kod",
    document: "dokument",
    of: "av",
    used: "använd",
    "Open item location": "Öppna objektets plats",
    "Are you sure you want to delete": "Är du säker att du vill radera",
    "these items:": "de här objekten:",
    "this item:": "detta objekt:",
    "Delete files": "Radera filer",
    and: "och",
    "more file(s)": "fler fil(er)",
    "Close the editor": "Stäng redigeraren",
    "Close this file": "Stäng den här filen",
    "Owner": "Ägare",
    "Permissions": "Rättigheter",
    "Change Permissions": "Ändra Rättigheter",
    "Set": "Sätt",
    "Extract": "Extrahera",
    "Extract directory": "Extrahera mapp",
    "Extracting...": "Extraherar...",
    "Compress": "Komprimera",
    "Compressing...": "Komprimerar...",
};